"""
Scene Builder — converts a movie-aware narration script into a full scene plan.
Each scene carries a precise YouTube search_query (generated by ScriptWriter via Gemini)
instead of generic stock-footage keywords.
"""

import json
import re
from pathlib import Path
from typing import Dict, List

# Rough words-per-minute for TTS duration estimation
WPM = 150


class SceneBuilder:
    """Enrich a script dict into a full scene-plan JSON ready for yt-dlp fetching."""

    # ── public ──────────────────────────────────────────────────
    def build(self, script: Dict) -> Dict:
        """
        Takes a script dict (from ScriptWriter/Gemini) and produces a scene plan
        with all fields needed for YouTube clip fetching and FFmpeg rendering.
        """
        topic = script.get("topic", "unknown")
        style = script.get("style", "documentary")
        is_movie = script.get("is_movie", False)
        director = script.get("director", "")
        year = script.get("year", "")

        enriched_scenes: List[Dict] = []

        for scene in script["scenes"]:
            narration = scene.get("narration", "")
            scene_id = scene.get("scene_id", len(enriched_scenes) + 1)

            # Use Gemini-generated search_query directly — it's movie-specific.
            # Fall back to a safe movie-title query only if missing.
            search_query = scene.get("search_query") or self._fallback_query(
                topic, scene_id, scene.get("clip_type", "scene")
            )

            # Build a ranked list of YouTube search queries to try in order.
            # First query is the Gemini-generated one; fallbacks broaden the search.
            query_variants = self._build_query_variants(
                primary=search_query,
                topic=topic,
                scene_id=scene_id,
                clip_type=scene.get("clip_type", "scene"),
            )

            est_dur = scene.get("estimated_duration") or self._estimate_duration(narration)

            enriched_scenes.append({
                "scene_id": scene_id,
                "type": scene.get("type", "body"),
                "narration": narration,

                # YouTube search — primary query + fallback variants
                "search_query": search_query,
                "query_variants": query_variants,
                "clip_type": scene.get("clip_type", "scene"),

                # Media info filled in by YouTubeFetcher
                "media_type": "video",
                "media_file": None,
                "yt_video_id": None,
                "yt_title": None,

                # TTS filled in by TTSEngine
                "tts_file": None,
                "tts_duration": None,

                "estimated_duration": round(est_dur, 2),

                # Cinematic metadata (passthrough from ScriptWriter)
                "emotion": scene.get("emotion", "epic"),
                "intensity": scene.get("intensity", 0.5),
                "pacing": scene.get("pacing", "medium"),
                "camera_move": scene.get("camera_move", "static_wide"),
                "color_grade": scene.get("color_grade", "muted_film"),
                "music_cue": scene.get("music_cue", "hold"),
                "cut_style": scene.get("cut_style", "hard_cut"),
            })

        return {
            "topic": topic,
            "style": style,
            "is_movie": is_movie,
            "director": director,
            "year": year,
            "total_scenes": len(enriched_scenes),
            "scenes": enriched_scenes,
        }

    # ── helpers ─────────────────────────────────────────────────
    @staticmethod
    def _fallback_query(topic: str, scene_id: int, clip_type: str) -> str:
        """Generate a safe movie-specific YouTube query when Gemini didn't provide one."""
        suffixes = {
            "trailer": "official trailer HD",
            "scene": "best scene HD",
            "featurette": "behind the scenes",
            "review": "movie review",
            "breakdown": "scene breakdown",
        }
        suffix = suffixes.get(clip_type, "clip HD")
        return f"{topic} {suffix}"

    @staticmethod
    def _build_query_variants(
        primary: str, topic: str, scene_id: int, clip_type: str
    ) -> List[str]:
        """
        Return an ordered list of YouTube search queries.
        The fetcher tries them in order until it finds a downloadable clip.
        """
        variants = [primary]

        # Add progressively broader fallbacks
        if "trailer" not in primary.lower():
            variants.append(f"{topic} official trailer")
        if "scene" not in primary.lower():
            variants.append(f"{topic} best scenes HD")
        variants.append(f"{topic} movie clip")
        variants.append(f"{topic} {clip_type}")

        # Deduplicate while preserving order
        seen = set()
        deduped = []
        for v in variants:
            if v not in seen:
                seen.add(v)
                deduped.append(v)
        return deduped

    @staticmethod
    def _estimate_duration(narration: str) -> float:
        """Estimate TTS duration in seconds from word count."""
        word_count = len(narration.split())
        duration = (word_count / WPM) * 60
        return max(3.0, min(duration, 15.0))

    # ── serialise ───────────────────────────────────────────────
    @staticmethod
    def save(scene_plan: Dict, path: Path):
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(scene_plan, f, indent=2, ensure_ascii=False)

    @staticmethod
    def load(path: Path) -> Dict:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)